### ISSUE TITLE
Suggestion: Support for HTTP2

### ISSUE THREAD

**Issue by dharvey-consbio** [spyoungtech/grequests#140]
Currently `requests` doesn't support HTTP2, so this would represent a significant architectural change, but other libraries like `hyper` do:

https://hyper.readthedocs.io/en/latest/

Are there any plans to add support for HTTP2 in the future?

**Comment by spyoungtech** [comment]
Thanks, that's a great question.  Since `grequests` relies on `requests` it'd probably be up to `requests` to support HTTP2 first before this library is able to do so as well. It'll also depend on how nice gevent plays with a version of requests that supports http2.

So, if/when that becomes available in `requests`, I'd be happy to work on investigating adding that support to `grequests` -- though I imagine it might even just come to us here for free through use of `requests.Session` or something like that.

Hope that makes sense.

**Comment by dharvey-consbio** [comment]
Thanks for the prompt feedback! I'll close the issue since `requests` has not yet made that leap, although there was some talk about it at PyCon 2017 during Cory Benfield's presentation:

https://us.pycon.org/2017/schedule/presentation/71/

Thanks again, and may HTTP2 come soon to `requests`!
