### ISSUE TITLE
How to show a status code

### ISSUE THREAD

**Issue by CyberRaven** [spyoungtech/grequests#149]
Hi 

I'm using a grequests to send parallel requests.
I'm trying to find a way that I can print a status code for every iteration , but I didn't 

a snippet of my code:
```
for payload in file:
  i += 1
  result = grequests.head(url + "/" + payload)
  print(" [ {} : {} ]\t\t\t\t\t[{}]\t\t\t\t[{}/{}] ".format(i,lines_count,result.status_code,url,result.url) )
```
problem type: **AttributeError: 'AsyncRequest' object has no attribute 'status_code'**
I tried to use requests's syntax but it didn't help
could you help me please?

**Comment by spyoungtech** [comment]
`grequests` works a bit differently than `requests`. The methods create request objects which must be sent in order to get a result. You do this via the `map` or `imap` functions, as described in the README. 

To get output during the mapping process, you can specify a callback and/or error handler.

**Comment by spyoungtech** [comment]
Since this seems like a user error, I will close for now.
