### ISSUE TITLE
why size is no affect in map？

### ISSUE THREAD

**Issue by wonb168** [spyoungtech/grequests#158]
I split the urls myself，cost about 6 minutes，
```
rst=[]
size=10
for i in range(98):# 5m 58.8s
    if i%size==0:
        print(i,i+size)
        rs = (grequests.get(u) for u in urls[i:i+size])
        rst.extend(grequests.map(rs))
```
But, if use size in map, 20minusts ago, no output, I killed it:
```
rs = (grequests.get(u) for u in urls)
rst=grequests.map(rs,size=10)
```
Why?
And how to speed it, thanks!

**Comment by spyoungtech** [comment]
The behavior you're seeing is probably because one or more of your requests is hanging. Add the `timeout` keyword argument the request to be sure one request does not hang up your entire request list.


Can't reproduce this using httpbin.org -- must be a reliability problem with the server you're contacting.

In my own testing, `map(rs, size=10)` is significantly faster.

```python
urls = [f'https://httpbin.org/status/200' for _ in range(100)]
>>> timeit.timeit(sized_map, globals=globals(), number=1)
4.341320300009102
>>> timeit.timeit(manual_map, globals=globals(), number=1) 
6.858147199964151
```
