### ISSUE TITLE
Params of get/post functions

### ISSUE THREAD

**Issue by latot** [spyoungtech/grequests#161]
Hi all, I notice something when I was using timeout in post, I notice the functions fails because is not a params.

This is confusing because in the README:
```
The HTTP verb methods in grequests (grequests.get, grequests.post, etc) accept all the same keyword arguments as in the requests library.
```

So, is not like every keywords is available.

In the particular case of timeout, seems confusing, we need to use it from map and imap does not have it:
```
def map(requests, stream=False, size=None, exception_handler=None, gtimeout=None):
def imap(requests, stream=False, size=2, exception_handler=None):
```

So..., the timeout is avaliable from map as ```gtimeout``` but in the case of imap there is no keyword for that.

The lib actually is pretty easy to use, sort this things I think will helps to down even more the learn curve.

Thx!

**Comment by spyoungtech** [comment]
In the `map` method, the `gtimeout` parameter is passed to `gevent`'s [`joinall` method](https://www.gevent.org/api/gevent.html#gevent.joinall). This is not to be confused with the [`timeout` parameter](https://requests.readthedocs.io/en/stable/user/quickstart/#timeouts) normally accepted by the HTTP verb methods in `requests`/`grequests`.  
In the `imap` method, we do not use `gevent.joinall` so there's no opportunity to provide a timeout parameter in this case with respect to how gevent handles the eventlets. I'm not sure if that's something that can be reasonably changed or not.


What might work for you is providing the `timeout` parameter to the request instead of relying on the gevent timeout.

```python
rs = [grequests.get(url, timeout=10) for url in urls]
grequests.map(rs)
```

Hope that helps.

**Comment by latot** [comment]
Hi, I try it with post, sadly fails, I want to show a test, but I need to wait until https://github.com/spyoungtech/grequests/issues/162

**Comment by latot** [comment]
mm, no idea why no works, I'll close it. Thx!
