### ISSUE TITLE
Request for image

### ISSUE THREAD

**Issue by pasa13142** [spyoungtech/grequests#165]
Hello, Thanks for this amazing repo. I would like to request for images. 

`requests.get(url, stream=True).content` 

Works for me to get image from URL.

But when i try 

`import grequests
import requests

urls = URLS[:8]
unsent_request = (grequests.get(url) for url in urls)

results = grequests.map(unsent_request) 
results`

It returns None. Any suggestions?

**Comment by spyoungtech** [comment]
I'm not sure I can reproduce this problem. If you get `None` back in your results, it's usually because the request failed for some reason. You can add an exception handler to dig deeper into that.

But the following code should work for retrieving images:

```python
import grequests

image_types = ['jpeg', 'png', 'svg']
urls = [f'https://httpbin.org/image/{it}' for it in image_types]
reqs = [grequests.get(url) for url in urls]

for resp in grequests.map(reqs):
    print(resp, len(resp.content))
```

And should get an output something like:

```
<Response [200]> 35588
<Response [200]> 8090
<Response [200]> 8984
```

**Comment by pasa13142** [comment]
Thank you! I got:

`maximum recursion depth exceeded while calling a Python object` 
error with your handler and set it to 5000 and it works now. Thanks!
