### ISSUE TITLE
gtimeout does not works with imap_enumerated

### ISSUE THREAD

**Issue by latot** [spyoungtech/grequests#169]
I have used in the past this type of line:

```
grequests.map(reqs, exception_handler = lambda x, e: print(e), gtimeout = 600, size = size)
```

But the same with imap_enumerated does not works:
```
grequests.imap_enumerated(reqs, exception_handler = lambda x, e: print(e), gtimeout = 600, size = size)
TypeError: imap_enumerated() got an unexpected keyword argument 'gtimeout'
```

Thx!

**Comment by spyoungtech** [comment]
The `gtimeout` argument is not supported in `imap` or `imap_enumerated`. This is because responses are returned immediately as they become available and not joined before returning results, like in `map`.

Note that you can still make use of the `timeout` keyword parameter for each individual request (one such example is in the README).

Hope that helps.
