### ISSUE TITLE
Flag to print the request being executed

### ISSUE THREAD

**Issue by utsavtiwary04** [spyoungtech/grequests#170]
Can we please add a flag, which when set to "True" can print some information about the request being executed ? Happy to raise a PR if you approve @spyoungtech

**Comment by spyoungtech** [comment]
Since `grequests` doesn't really do much but wrap requests with gevent, I'm not sure this is the place to add such functionality.

`urllib3` (which underlies `requests`) has some logging builtin.

You can already [log requests when they are made](https://stackoverflow.com/a/16337639/5747944) using the builtin logging module. As a simple example, you can expose the HTTP debug logs just by enabling debug logging:

```python
import grequests
import logging
logging.basicConfig
logging.basicConfig(level=logging.DEBUG)
reqs = [grequests.get(f'https://httpbin.org/status/{i}') for i in range(200,210)]
grequests.map(reqs)
```

You can also use all the same functionality in `requests` like [hooks](https://requests.readthedocs.io/en/latest/user/advanced/) to hook into responses as well.

```python
import grequests
import requests

def log_requests(response, *args, **kwargs):
    request = response.request
    print(request.url) # or whatever

session = requests.Session()
session.hooks['response'].append(log_requests)

reqs = [grequests.get(f'https://httpbin.org/status/{i}', session=session) for i in range(200, 2010)]
grequests.map(reqs)
```


There's probably a few other ways, too.

**Comment by utsavtiwary04** [comment]
Thank you @spyoungtech 
Closing this.
