### ISSUE TITLE
set specific version in setup.py

### ISSUE THREAD

**Issue by pydavid** [spyoungtech/grequests#90]
Hi,

it would be great if in the setup.py, specific versions are required as,
 for example, with gevent 0.9.0 grequests doesn't work.

**Comment by spyoungtech** [comment]
Thanks for the suggestion. Because `grequests` works with many versions of `gevent`, it's best we don't pin to specific versions. I did try to install gevent 0.9.0 to confirm, but it seems no such version is on PyPI (anymore?).

It's also worth mentioning that compatibility may also depend on combinations of: your version of python, version of gevent, and potential conflicts with other packages that also use `gevent`.
